### ISSUE TITLE
Styles that should be in breakpoints should not be in %col-margin-base

### ISSUE THREAD

**Issue by ashleykolodziej** [bu-ist/responsive-foundation#17]
Margin and removing margin-right should be moved out of base placeholder to breakpoint-specific placeholders to avoid conflicts when using placeholders. Issues commented below.

``` css
%col-margin-base {
    /* These classes are using %col-margin-base. */
    margin: $grid-margin-width#{"%"}; // Should start at appropriate breakpoint
    margin-top: 0;
    padding: 20px;
    @include breakpoint(sm) { // Should start at appropriate breakpoint
        margin-right: 0;
    }
}
```
