### ISSUE TITLE
BU-Collapsible needs additional style for BULP Custom HTML Block

### ISSUE THREAD

**Issue by tspears1** [bu-ist/responsive-foundation#273]
## Description
BULP (BU Landing Pages) has added a new section, the Custom HTML Section. When a `bu-collapsible` is used in the section, it rides too close to the right border so additional padding is needed.

## Solution

In `/responsive-foundation/burf-customizations/content/_collapsibles.scss` add:

```SCSS
.bu_collapsible {
    .bulp-custom-html & {
        padding-right: 45px;
    }
}
```
