### ISSUE TITLE
$fontFamily-button uses wrong CSS property

### ISSUE THREAD

**Issue by ashleykolodziej** [bu-ist/responsive-foundation#7]
$fontFamily-button is mapped to font-size instead of font-family in burf-base/_base-forms.scss (line 320):

``` css
.button {
// (...)
    font-size: $fontSize-button;
    font-size: $fontFamily-button;
}
```
